/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poo.ads;

public class App {

    public static void main(String[] args) {
         Ponto a = new Ponto(1, 2);

         Ponto b = new Ponto(3, 4);

        System.out.println(a.ditancia(b));

    }
}
