/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        Carro garagem = new Carro("fusca", "branco", new Motor(52,1500));

        ArrayList<Motor>estante = new ArrayList<>();

        estante.add(garagem.getMotor());

        garagem.setMotor(new Motor(70,2000));

        estante.add(garagem.getMotor());

        garagem = new Carro("Uno", "prata", new Motor(47, 1900));

        estante.add(garagem.getMotor());







    }
}
