/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;
import com.google.common.collect.Ordering;

import java.util.*;

public class App {

    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);

        ArrayList<String> nomes = new ArrayList<>();
        String s = "Joana";

        nomes.add(s);
        nomes.add("Juca");

        //System.out.println(nomes);

        //System.out.println(nomes.size());

        /*if (!nomes.isEmpty()){
            //nomes.removeAll(nomes);
            //ou
            nomes.clear();
        }*/

        /*
        nomes.remove("Juca");
        //ou
        int pos = nomes.indexOf("Juca");
        nomes.remove(pos);
        */

        //String[] v = (String[]) nomes.toArray();

        //Correção de tipos ou typecasting
        //double d = 2.3;
        //int i = (int) d;


        //for i
        /*for(int i = 0; i < nomes.size(); i++) {
            System.out.println("Nome: "+ nomes.get(i));
        }*/

        //for each
        /*for (String elementos: nomes){
            System.out.println("Nome: "+ elementos);
        }*/


        //usando lambda
        //nomes.forEach(elementos-> System.out.println("Nome: "+ elementos));

        //usando lambda
        //nomes.forEach(elementos-> {
        // System.out.println("Nome: "+ elementos);
        //se tiver mais de uma linha
        // });

        //para imprimir so os argumentos
        //nomes.forEach(System.out::println);


        //digitar numeros do teclado, enquando não digitar 999 ele continua solicitando

        /*ArrayList<Integer> lista = new ArrayList<>();
        int i = 0;

        while (i != 999) {
            System.out.println("Entre com um numero inteiro: ");
            i = teclado.nextInt();
            if (i != 999) {
                lista.add(i);
            }
        }
        System.out.println(" ");
        Collections.sort(lista);
        lista.forEach(System.out::println);*/


        Stack<Integer>listaPilha = new Stack<>();
        int i = 0;

        while (i != 999) {
            System.out.println("Entre com um numero inteiro: ");
            i = teclado.nextInt();
            if (i != 999) {
                listaPilha.push(i);
            }
        }
        System.out.println(" ");

        while (!listaPilha.isEmpty()){
            System.out.println(listaPilha.pop());
        }
    }
}
