/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public static void main(String[] args) {

        Arqueiro arqueiro = new Arqueiro(3);
        Cavaleiro cavaleiro = new Cavaleiro("escudo");
        Aldeao aldeao = new Aldeao("faca");

        System.out.println(aldeao.mover());

        Soldado s = new Soldado(5,6,10);







    }
}
