/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poo.ads;


public class App {

    public static void main(String[] args) {
        Agenda agenda = new Agenda();


           }
}
