/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import edu.princeton.cs.algs4.Draw;

import java.awt.*;
import java.awt.dnd.DragGestureEvent;

public class App {

    public static void main(String[] args) {
        Draw draw = new Draw();

        /*draw.setPenColor(Color.CYAN);
        draw.text(.5, .5,"Joana");

        draw.filledRectangle(.5, .5, .3, .5);

        draw.filledSquare(.5, .5, .2);

        draw.setPenColor(Color.RED);
        draw.text(.5, .5,"Joana");
        */


        draw.setCanvasSize(800,600);
        draw.setXscale(0,800);
        draw.setYscale(0,600);

        draw.setPenColor(Color.RED);
        draw.text(400,300, "Joana");

        //draw.picture(400,300, "IMAGEM.jpg");



    }
}
