/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayList;
import java.util.HashMap;

public class App {
    public static void main(String[] args) {


    }
}
