/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poo;

import poo.produtos.Celular;
import poo.produtos.Dimensao;
import poo.produtos.SemFio;
import poo.produtos.Telefone;

public class App {

    public static void main(String[] args) {
        Dimensao dimensao1 = new Dimensao(3,7, 10);
        Telefone telefone1 = new Telefone("468GHS", "69B4DGF6", "Samsung", 10, dimensao1);

        Dimensao dimensao2 = new Dimensao(5,4, 7);
        SemFio telefone2 = new SemFio("SDFGS", "FDS6F", "Iphone", 8, dimensao2, 15, 4, 9);

        Telefone telefone3 = new SemFio("SDFGS", "FDS6F", "Iphone", 8, dimensao2, 15, 4, 9);

        //Não pode, Semfio não pode ser um telefone
       // SemFio telefone4 = new Telefone("SDFGS", "FDS6F", "Iphone", 8, dimensao2, 15, 4, 9);

        SemFio aux = telefone2;

        System.out.println(telefone1.imprimirDados());
        System.out.println(telefone2.imprimirDados());

        System.out.println(telefone3.imprimirDados());

        System.out.println(aux.imprimirDados());

        //Só imprime o número 2
        int f = (int)2.5;
        System.out.println(f);
/*
        Telefone t;
        SemFio s;
        Celular c;
        Celular d;

        Dimensao dimensao3 = new Dimensao(3,7, 10);
        t = new Celular("SDFGS", "FDS6F", "Iphone",10, dimensao3,10, 2,3,"kajss");
        c = new Celular("SDFGS", "FDS6F", "Iphone",10, dimensao3,10, 2,3,"kajss");


        //c.setSistemaOperacional("ios");
        //((Celular)t).setSistemaOperacional("windows");
        d = c;
        d = (Celular) t; //se não estiver realmente um celular dentro da variavel telefone da problema

*/
        Telefone[] t = new Telefone[4];
        t[0] = new Telefone("468GHS", "69B4DGF6", "Samsung", 10, dimensao1);
        t[1] = new Celular("SDFGS", "FDS6F", "Iphone",10, dimensao1,10, 2,3,"kajss");
        t[2] = new Celular("SDFGS", "FDS6F", "Iphone",10, dimensao1,10, 2,3,"kajss");
        t[3] = new SemFio("SDFGS", "FDS6F", "Iphone", 8, dimensao2, 15, 4, 9);


        for (Telefone tel : t){
            System.out.println(tel.imprimirDados());

            if (tel instanceof Celular){ // verificando se o telefone é uma instancia de celular
                System.out.println(((Celular)tel).getSistemaOperacional());
            }
        }


    }
}

