/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poo.ads;


public class App {
    public static void main(String[] args) {

        Horario h = new Horario(23,25,2);
        Horario v = new Horario(20,20,1);

        System.out.println(h.toString());

        System.out.println(h.subtracaoHora(v));

        System.out.println(h.extenso(h));
    }
}
